pages:
  stage: deploy
  variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
  script:
    - mkdir -p public
    - cp index.html entries.json public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
